name: 'Check Branches'

on:
  pull_request:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'master' && github.head_ref != 'development'
        run: |
          echo "ERROR: You can only merge to master from development."
          exit 1