name: 'Check Branch'

on:
  pull_request:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'production' && github.head_ref != 'master'
        run: |
          echo "ERROR: You can only merge to production from master."
          exit 1